/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.Connectionpersimtime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConnectionpersimtimeRecord extends UpdatableRecordImpl<ConnectionpersimtimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.connectionpersimtime.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.connectionpersimtime.iotdevices</code>.
     */
    public void setIotdevices(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime.iotdevices</code>.
     */
    public Integer getIotdevices() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.connectionpersimtime.edgehost</code>.
     */
    public void setEdgehost(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime.edgehost</code>.
     */
    public String getEdgehost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.connectionpersimtime.cps_time</code>.
     */
    public void setCpsTime(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.connectionpersimtime.cps_time</code>.
     */
    public Double getCpsTime() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConnectionpersimtimeRecord
     */
    public ConnectionpersimtimeRecord() {
        super(Connectionpersimtime.CONNECTIONPERSIMTIME);
    }

    /**
     * Create a detached, initialised ConnectionpersimtimeRecord
     */
    public ConnectionpersimtimeRecord(Integer uniqueEntryId, Integer iotdevices, String edgehost, Double cpsTime) {
        super(Connectionpersimtime.CONNECTIONPERSIMTIME);

        setUniqueEntryId(uniqueEntryId);
        setIotdevices(iotdevices);
        setEdgehost(edgehost);
        setCpsTime(cpsTime);
        resetChangedOnNotNull();
    }
}
