/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.Powerutilisationhistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PowerutilisationhistoryRecord extends UpdatableRecordImpl<PowerutilisationhistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.powerutilisationhistory.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.powerutilisationhistory.dcname</code>.
     */
    public void setDcname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory.dcname</code>.
     */
    public String getDcname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.powerutilisationhistory.puh_name</code>.
     */
    public void setPuhName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory.puh_name</code>.
     */
    public String getPuhName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.powerutilisationhistory.starttime</code>.
     */
    public void setStarttime(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory.starttime</code>.
     */
    public Double getStarttime() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.powerutilisationhistory.usedmips</code>.
     */
    public void setUsedmips(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.powerutilisationhistory.usedmips</code>.
     */
    public Double getUsedmips() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PowerutilisationhistoryRecord
     */
    public PowerutilisationhistoryRecord() {
        super(Powerutilisationhistory.POWERUTILISATIONHISTORY);
    }

    /**
     * Create a detached, initialised PowerutilisationhistoryRecord
     */
    public PowerutilisationhistoryRecord(Integer uniqueEntryId, String dcname, String puhName, Double starttime, Double usedmips) {
        super(Powerutilisationhistory.POWERUTILISATIONHISTORY);

        setUniqueEntryId(uniqueEntryId);
        setDcname(dcname);
        setPuhName(puhName);
        setStarttime(starttime);
        setUsedmips(usedmips);
        resetChangedOnNotNull();
    }
}
