/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.TimedScc;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimedSccRecord extends UpdatableRecordImpl<TimedSccRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.timed_scc.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.timed_scc.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.timed_scc.time_of_update</code>.
     */
    public void setTimeOfUpdate(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.timed_scc.time_of_update</code>.
     */
    public Double getTimeOfUpdate() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.timed_scc.networkneighbours1</code>.
     */
    public void setNetworkneighbours1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.timed_scc.networkneighbours1</code>.
     */
    public String getNetworkneighbours1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.timed_scc.networkneighbours2</code>.
     */
    public void setNetworkneighbours2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.timed_scc.networkneighbours2</code>.
     */
    public String getNetworkneighbours2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.timed_scc.networkneighbours3</code>.
     */
    public void setNetworkneighbours3(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.timed_scc.networkneighbours3</code>.
     */
    public String getNetworkneighbours3() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.timed_scc.networkneighbours4</code>.
     */
    public void setNetworkneighbours4(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.timed_scc.networkneighbours4</code>.
     */
    public String getNetworkneighbours4() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimedSccRecord
     */
    public TimedSccRecord() {
        super(TimedScc.TIMED_SCC);
    }

    /**
     * Create a detached, initialised TimedSccRecord
     */
    public TimedSccRecord(Integer uniqueEntryId, Double timeOfUpdate, String networkneighbours1, String networkneighbours2, String networkneighbours3, String networkneighbours4) {
        super(TimedScc.TIMED_SCC);

        setUniqueEntryId(uniqueEntryId);
        setTimeOfUpdate(timeOfUpdate);
        setNetworkneighbours1(networkneighbours1);
        setNetworkneighbours2(networkneighbours2);
        setNetworkneighbours3(networkneighbours3);
        setNetworkneighbours4(networkneighbours4);
        resetChangedOnNotNull();
    }
}
