/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables.records;


import org.jooq.impl.TableRecordImpl;

import uk.ncl.giacomobergami.utils.database.jooq.tables.VehinformationImport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehinformationImportRecord extends TableRecordImpl<VehinformationImportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vehinformation_import.angle</code>.
     */
    public void setAngle(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.angle</code>.
     */
    public Double getAngle() {
        return (Double) get(0);
    }

    /**
     * Setter for <code>public.vehinformation_import.vehicle_id</code>.
     */
    public void setVehicleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.vehicle_id</code>.
     */
    public String getVehicleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vehinformation_import.lane</code>.
     */
    public void setLane(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.lane</code>.
     */
    public String getLane() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vehinformation_import.pos</code>.
     */
    public void setPos(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.pos</code>.
     */
    public Double getPos() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.vehinformation_import.simtime</code>.
     */
    public void setSimtime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.simtime</code>.
     */
    public Double getSimtime() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.vehinformation_import.slope</code>.
     */
    public void setSlope(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.slope</code>.
     */
    public Double getSlope() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.vehinformation_import.speed</code>.
     */
    public void setSpeed(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.speed</code>.
     */
    public Double getSpeed() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.vehinformation_import.vehicle_type</code>.
     */
    public void setVehicleType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.vehicle_type</code>.
     */
    public String getVehicleType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.vehinformation_import.x</code>.
     */
    public void setX(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.x</code>.
     */
    public Double getX() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.vehinformation_import.y</code>.
     */
    public void setY(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.vehinformation_import.y</code>.
     */
    public Double getY() {
        return (Double) get(9);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehinformationImportRecord
     */
    public VehinformationImportRecord() {
        super(VehinformationImport.VEHINFORMATION_IMPORT);
    }

    /**
     * Create a detached, initialised VehinformationImportRecord
     */
    public VehinformationImportRecord(Double angle, String vehicleId, String lane, Double pos, Double simtime, Double slope, Double speed, String vehicleType, Double x, Double y) {
        super(VehinformationImport.VEHINFORMATION_IMPORT);

        setAngle(angle);
        setVehicleId(vehicleId);
        setLane(lane);
        setPos(pos);
        setSimtime(simtime);
        setSlope(slope);
        setSpeed(speed);
        setVehicleType(vehicleType);
        setX(x);
        setY(y);
        resetChangedOnNotNull();
    }
}
