/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.dynamicinformation_di_entry_id_seq</code>
     */
    public static final Sequence<Integer> DYNAMICINFORMATION_DI_ENTRY_ID_SEQ = Internal.createSequence("dynamicinformation_di_entry_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
