/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model;


import uk.ncl.rohingillgallon.jooq.model.tables.Accuratebatteryinfo;
import uk.ncl.rohingillgallon.jooq.model.tables.Applist;
import uk.ncl.rohingillgallon.jooq.model.tables.Bandwidthshareinfo;
import uk.ncl.rohingillgallon.jooq.model.tables.Connectionpersimtime;
import uk.ncl.rohingillgallon.jooq.model.tables.Datacenterenergyconsumption;
import uk.ncl.rohingillgallon.jooq.model.tables.Historyentry;
import uk.ncl.rohingillgallon.jooq.model.tables.Hostpowerconsumption;
import uk.ncl.rohingillgallon.jooq.model.tables.Neighbourschange;
import uk.ncl.rohingillgallon.jooq.model.tables.Osmoticappsstats;
import uk.ncl.rohingillgallon.jooq.model.tables.Overallappresults;
import uk.ncl.rohingillgallon.jooq.model.tables.Powerutilisationhistory;
import uk.ncl.rohingillgallon.jooq.model.tables.Rsuinformation;
import uk.ncl.rohingillgallon.jooq.model.tables.Switchpowerconsumption;
import uk.ncl.rohingillgallon.jooq.model.tables.TimedScc;
import uk.ncl.rohingillgallon.jooq.model.tables.Vehinformation;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.accuratebatteryinfo</code>.
     */
    public static final Accuratebatteryinfo ACCURATEBATTERYINFO = Accuratebatteryinfo.ACCURATEBATTERYINFO;

    /**
     * The table <code>public.applist</code>.
     */
    public static final Applist APPLIST = Applist.APPLIST;

    /**
     * The table <code>public.bandwidthshareinfo</code>.
     */
    public static final Bandwidthshareinfo BANDWIDTHSHAREINFO = Bandwidthshareinfo.BANDWIDTHSHAREINFO;

    /**
     * The table <code>public.connectionpersimtime</code>.
     */
    public static final Connectionpersimtime CONNECTIONPERSIMTIME = Connectionpersimtime.CONNECTIONPERSIMTIME;

    /**
     * The table <code>public.datacenterenergyconsumption</code>.
     */
    public static final Datacenterenergyconsumption DATACENTERENERGYCONSUMPTION = Datacenterenergyconsumption.DATACENTERENERGYCONSUMPTION;

    /**
     * The table <code>public.historyentry</code>.
     */
    public static final Historyentry HISTORYENTRY = Historyentry.HISTORYENTRY;

    /**
     * The table <code>public.hostpowerconsumption</code>.
     */
    public static final Hostpowerconsumption HOSTPOWERCONSUMPTION = Hostpowerconsumption.HOSTPOWERCONSUMPTION;

    /**
     * The table <code>public.neighbourschange</code>.
     */
    public static final Neighbourschange NEIGHBOURSCHANGE = Neighbourschange.NEIGHBOURSCHANGE;

    /**
     * The table <code>public.osmoticappsstats</code>.
     */
    public static final Osmoticappsstats OSMOTICAPPSSTATS = Osmoticappsstats.OSMOTICAPPSSTATS;

    /**
     * The table <code>public.overallappresults</code>.
     */
    public static final Overallappresults OVERALLAPPRESULTS = Overallappresults.OVERALLAPPRESULTS;

    /**
     * The table <code>public.powerutilisationhistory</code>.
     */
    public static final Powerutilisationhistory POWERUTILISATIONHISTORY = Powerutilisationhistory.POWERUTILISATIONHISTORY;

    /**
     * The table <code>public.rsuinformation</code>.
     */
    public static final Rsuinformation RSUINFORMATION = Rsuinformation.RSUINFORMATION;

    /**
     * The table <code>public.switchpowerconsumption</code>.
     */
    public static final Switchpowerconsumption SWITCHPOWERCONSUMPTION = Switchpowerconsumption.SWITCHPOWERCONSUMPTION;

    /**
     * The table <code>public.timed_scc</code>.
     */
    public static final TimedScc TIMED_SCC = TimedScc.TIMED_SCC;

    /**
     * The table <code>public.vehinformation</code>.
     */
    public static final Vehinformation VEHINFORMATION = Vehinformation.VEHINFORMATION;
}
