/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.rohingillgallon.jooq.model.Keys;
import uk.ncl.rohingillgallon.jooq.model.Public;
import uk.ncl.rohingillgallon.jooq.model.tables.records.AccuratebatteryinfoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accuratebatteryinfo extends TableImpl<AccuratebatteryinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.accuratebatteryinfo</code>
     */
    public static final Accuratebatteryinfo ACCURATEBATTERYINFO = new Accuratebatteryinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccuratebatteryinfoRecord> getRecordType() {
        return AccuratebatteryinfoRecord.class;
    }

    /**
     * The column <code>public.accuratebatteryinfo.unique_entry_id</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.accuratebatteryinfo.iotdevicename</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, String> IOTDEVICENAME = createField(DSL.name("iotdevicename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo.consumption</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, Double> CONSUMPTION = createField(DSL.name("consumption"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo.flowid</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, Integer> FLOWID = createField(DSL.name("flowid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo.nopackets</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, Double> NOPACKETS = createField(DSL.name("nopackets"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.accuratebatteryinfo.time</code>.
     */
    public final TableField<AccuratebatteryinfoRecord, Double> TIME = createField(DSL.name("time"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Accuratebatteryinfo(Name alias, Table<AccuratebatteryinfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Accuratebatteryinfo(Name alias, Table<AccuratebatteryinfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.accuratebatteryinfo</code> table reference
     */
    public Accuratebatteryinfo(String alias) {
        this(DSL.name(alias), ACCURATEBATTERYINFO);
    }

    /**
     * Create an aliased <code>public.accuratebatteryinfo</code> table reference
     */
    public Accuratebatteryinfo(Name alias) {
        this(alias, ACCURATEBATTERYINFO);
    }

    /**
     * Create a <code>public.accuratebatteryinfo</code> table reference
     */
    public Accuratebatteryinfo() {
        this(DSL.name("accuratebatteryinfo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AccuratebatteryinfoRecord, Integer> getIdentity() {
        return (Identity<AccuratebatteryinfoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccuratebatteryinfoRecord> getPrimaryKey() {
        return Keys.ACCURATEBATTERYINFO_PKEY;
    }

    @Override
    public Accuratebatteryinfo as(String alias) {
        return new Accuratebatteryinfo(DSL.name(alias), this);
    }

    @Override
    public Accuratebatteryinfo as(Name alias) {
        return new Accuratebatteryinfo(alias, this);
    }

    @Override
    public Accuratebatteryinfo as(Table<?> alias) {
        return new Accuratebatteryinfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Accuratebatteryinfo rename(String name) {
        return new Accuratebatteryinfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accuratebatteryinfo rename(Name name) {
        return new Accuratebatteryinfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accuratebatteryinfo rename(Table<?> name) {
        return new Accuratebatteryinfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo where(Condition condition) {
        return new Accuratebatteryinfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accuratebatteryinfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accuratebatteryinfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accuratebatteryinfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Accuratebatteryinfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Accuratebatteryinfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
