/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.rohingillgallon.jooq.model.Keys;
import uk.ncl.rohingillgallon.jooq.model.Public;
import uk.ncl.rohingillgallon.jooq.model.tables.records.DatacenterenergyconsumptionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Datacenterenergyconsumption extends TableImpl<DatacenterenergyconsumptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.datacenterenergyconsumption</code>
     */
    public static final Datacenterenergyconsumption DATACENTERENERGYCONSUMPTION = new Datacenterenergyconsumption();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatacenterenergyconsumptionRecord> getRecordType() {
        return DatacenterenergyconsumptionRecord.class;
    }

    /**
     * The column
     * <code>public.datacenterenergyconsumption.unique_entry_id</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption.hostenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, Double> HOSTENERGYCONSUMED = createField(DSL.name("hostenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption.switchenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, Double> SWITCHENERGYCONSUMED = createField(DSL.name("switchenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.datacenterenergyconsumption.totalenergyconsumed</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, Double> TOTALENERGYCONSUMED = createField(DSL.name("totalenergyconsumed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.datacenterenergyconsumption.dcname</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.datacenterenergyconsumption.finishtime</code>.
     */
    public final TableField<DatacenterenergyconsumptionRecord, Double> FINISHTIME = createField(DSL.name("finishtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Datacenterenergyconsumption(Name alias, Table<DatacenterenergyconsumptionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Datacenterenergyconsumption(Name alias, Table<DatacenterenergyconsumptionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.datacenterenergyconsumption</code> table
     * reference
     */
    public Datacenterenergyconsumption(String alias) {
        this(DSL.name(alias), DATACENTERENERGYCONSUMPTION);
    }

    /**
     * Create an aliased <code>public.datacenterenergyconsumption</code> table
     * reference
     */
    public Datacenterenergyconsumption(Name alias) {
        this(alias, DATACENTERENERGYCONSUMPTION);
    }

    /**
     * Create a <code>public.datacenterenergyconsumption</code> table reference
     */
    public Datacenterenergyconsumption() {
        this(DSL.name("datacenterenergyconsumption"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DatacenterenergyconsumptionRecord, Integer> getIdentity() {
        return (Identity<DatacenterenergyconsumptionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DatacenterenergyconsumptionRecord> getPrimaryKey() {
        return Keys.DATACENTERENERGYCONSUMPTION_PKEY;
    }

    @Override
    public Datacenterenergyconsumption as(String alias) {
        return new Datacenterenergyconsumption(DSL.name(alias), this);
    }

    @Override
    public Datacenterenergyconsumption as(Name alias) {
        return new Datacenterenergyconsumption(alias, this);
    }

    @Override
    public Datacenterenergyconsumption as(Table<?> alias) {
        return new Datacenterenergyconsumption(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Datacenterenergyconsumption rename(String name) {
        return new Datacenterenergyconsumption(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Datacenterenergyconsumption rename(Name name) {
        return new Datacenterenergyconsumption(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Datacenterenergyconsumption rename(Table<?> name) {
        return new Datacenterenergyconsumption(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption where(Condition condition) {
        return new Datacenterenergyconsumption(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Datacenterenergyconsumption where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Datacenterenergyconsumption where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Datacenterenergyconsumption where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Datacenterenergyconsumption where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Datacenterenergyconsumption whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
