/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.rohingillgallon.jooq.model.Keys;
import uk.ncl.rohingillgallon.jooq.model.Public;
import uk.ncl.rohingillgallon.jooq.model.tables.records.NeighbourschangeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Neighbourschange extends TableImpl<NeighbourschangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.neighbourschange</code>
     */
    public static final Neighbourschange NEIGHBOURSCHANGE = new Neighbourschange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NeighbourschangeRecord> getRecordType() {
        return NeighbourschangeRecord.class;
    }

    /**
     * The column <code>public.neighbourschange.unique_entry_id</code>.
     */
    public final TableField<NeighbourschangeRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.neighbourschange.rsu_id</code>.
     */
    public final TableField<NeighbourschangeRecord, String> RSU_ID = createField(DSL.name("rsu_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.neighbourschange.time_of_update</code>.
     */
    public final TableField<NeighbourschangeRecord, Double> TIME_OF_UPDATE = createField(DSL.name("time_of_update"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.neighbourschange.neighbour1</code>.
     */
    public final TableField<NeighbourschangeRecord, String> NEIGHBOUR1 = createField(DSL.name("neighbour1"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.neighbour2</code>.
     */
    public final TableField<NeighbourschangeRecord, String> NEIGHBOUR2 = createField(DSL.name("neighbour2"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.neighbour3</code>.
     */
    public final TableField<NeighbourschangeRecord, String> NEIGHBOUR3 = createField(DSL.name("neighbour3"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.ischange</code>.
     */
    public final TableField<NeighbourschangeRecord, String> ISCHANGE = createField(DSL.name("ischange"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.change1</code>.
     */
    public final TableField<NeighbourschangeRecord, String> CHANGE1 = createField(DSL.name("change1"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.change2</code>.
     */
    public final TableField<NeighbourschangeRecord, String> CHANGE2 = createField(DSL.name("change2"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.change3</code>.
     */
    public final TableField<NeighbourschangeRecord, String> CHANGE3 = createField(DSL.name("change3"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.neighbourschange.change4</code>.
     */
    public final TableField<NeighbourschangeRecord, String> CHANGE4 = createField(DSL.name("change4"), SQLDataType.VARCHAR(50), this, "");

    private Neighbourschange(Name alias, Table<NeighbourschangeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Neighbourschange(Name alias, Table<NeighbourschangeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.neighbourschange</code> table reference
     */
    public Neighbourschange(String alias) {
        this(DSL.name(alias), NEIGHBOURSCHANGE);
    }

    /**
     * Create an aliased <code>public.neighbourschange</code> table reference
     */
    public Neighbourschange(Name alias) {
        this(alias, NEIGHBOURSCHANGE);
    }

    /**
     * Create a <code>public.neighbourschange</code> table reference
     */
    public Neighbourschange() {
        this(DSL.name("neighbourschange"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<NeighbourschangeRecord, Integer> getIdentity() {
        return (Identity<NeighbourschangeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NeighbourschangeRecord> getPrimaryKey() {
        return Keys.NEIGHBOURSCHANGE_PKEY;
    }

    @Override
    public Neighbourschange as(String alias) {
        return new Neighbourschange(DSL.name(alias), this);
    }

    @Override
    public Neighbourschange as(Name alias) {
        return new Neighbourschange(alias, this);
    }

    @Override
    public Neighbourschange as(Table<?> alias) {
        return new Neighbourschange(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Neighbourschange rename(String name) {
        return new Neighbourschange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Neighbourschange rename(Name name) {
        return new Neighbourschange(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Neighbourschange rename(Table<?> name) {
        return new Neighbourschange(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange where(Condition condition) {
        return new Neighbourschange(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Neighbourschange where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Neighbourschange where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Neighbourschange where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Neighbourschange where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Neighbourschange whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
