/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.rohingillgallon.jooq.model.Keys;
import uk.ncl.rohingillgallon.jooq.model.Public;
import uk.ncl.rohingillgallon.jooq.model.tables.records.RsuinformationRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rsuinformation extends TableImpl<RsuinformationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.rsuinformation</code>
     */
    public static final Rsuinformation RSUINFORMATION = new Rsuinformation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RsuinformationRecord> getRecordType() {
        return RsuinformationRecord.class;
    }

    /**
     * The column <code>public.rsuinformation.unique_entry_id</code>.
     */
    public final TableField<RsuinformationRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.rsuinformation.rsu_id</code>.
     */
    public final TableField<RsuinformationRecord, String> RSU_ID = createField(DSL.name("rsu_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation.x</code>.
     */
    public final TableField<RsuinformationRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation.y</code>.
     */
    public final TableField<RsuinformationRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation.simtime</code>.
     */
    public final TableField<RsuinformationRecord, Double> SIMTIME = createField(DSL.name("simtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation.communication_radius</code>.
     */
    public final TableField<RsuinformationRecord, Double> COMMUNICATION_RADIUS = createField(DSL.name("communication_radius"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.rsuinformation.max_vehicle_communication</code>.
     */
    public final TableField<RsuinformationRecord, Double> MAX_VEHICLE_COMMUNICATION = createField(DSL.name("max_vehicle_communication"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Rsuinformation(Name alias, Table<RsuinformationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rsuinformation(Name alias, Table<RsuinformationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.rsuinformation</code> table reference
     */
    public Rsuinformation(String alias) {
        this(DSL.name(alias), RSUINFORMATION);
    }

    /**
     * Create an aliased <code>public.rsuinformation</code> table reference
     */
    public Rsuinformation(Name alias) {
        this(alias, RSUINFORMATION);
    }

    /**
     * Create a <code>public.rsuinformation</code> table reference
     */
    public Rsuinformation() {
        this(DSL.name("rsuinformation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<RsuinformationRecord, Integer> getIdentity() {
        return (Identity<RsuinformationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<RsuinformationRecord> getPrimaryKey() {
        return Keys.RSUINFORMATION_PKEY;
    }

    @Override
    public Rsuinformation as(String alias) {
        return new Rsuinformation(DSL.name(alias), this);
    }

    @Override
    public Rsuinformation as(Name alias) {
        return new Rsuinformation(alias, this);
    }

    @Override
    public Rsuinformation as(Table<?> alias) {
        return new Rsuinformation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rsuinformation rename(String name) {
        return new Rsuinformation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rsuinformation rename(Name name) {
        return new Rsuinformation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rsuinformation rename(Table<?> name) {
        return new Rsuinformation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation where(Condition condition) {
        return new Rsuinformation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rsuinformation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rsuinformation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rsuinformation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rsuinformation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rsuinformation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
