/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.rohingillgallon.jooq.model.Keys;
import uk.ncl.rohingillgallon.jooq.model.Public;
import uk.ncl.rohingillgallon.jooq.model.tables.records.VehinformationRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vehinformation extends TableImpl<VehinformationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vehinformation</code>
     */
    public static final Vehinformation VEHINFORMATION = new Vehinformation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehinformationRecord> getRecordType() {
        return VehinformationRecord.class;
    }

    /**
     * The column <code>public.vehinformation.di_entry_id</code>.
     */
    public final TableField<VehinformationRecord, Integer> DI_ENTRY_ID = createField(DSL.name("di_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vehinformation.vehicle_id</code>.
     */
    public final TableField<VehinformationRecord, String> VEHICLE_ID = createField(DSL.name("vehicle_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.x</code>.
     */
    public final TableField<VehinformationRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.y</code>.
     */
    public final TableField<VehinformationRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.angle</code>.
     */
    public final TableField<VehinformationRecord, Double> ANGLE = createField(DSL.name("angle"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.vehicle_type</code>.
     */
    public final TableField<VehinformationRecord, String> VEHICLE_TYPE = createField(DSL.name("vehicle_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.speed</code>.
     */
    public final TableField<VehinformationRecord, Double> SPEED = createField(DSL.name("speed"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.pos</code>.
     */
    public final TableField<VehinformationRecord, Double> POS = createField(DSL.name("pos"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.lane</code>.
     */
    public final TableField<VehinformationRecord, String> LANE = createField(DSL.name("lane"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.slope</code>.
     */
    public final TableField<VehinformationRecord, Double> SLOPE = createField(DSL.name("slope"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.vehinformation.simtime</code>.
     */
    public final TableField<VehinformationRecord, Double> SIMTIME = createField(DSL.name("simtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Vehinformation(Name alias, Table<VehinformationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Vehinformation(Name alias, Table<VehinformationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vehinformation</code> table reference
     */
    public Vehinformation(String alias) {
        this(DSL.name(alias), VEHINFORMATION);
    }

    /**
     * Create an aliased <code>public.vehinformation</code> table reference
     */
    public Vehinformation(Name alias) {
        this(alias, VEHINFORMATION);
    }

    /**
     * Create a <code>public.vehinformation</code> table reference
     */
    public Vehinformation() {
        this(DSL.name("vehinformation"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VehinformationRecord, Integer> getIdentity() {
        return (Identity<VehinformationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<VehinformationRecord> getPrimaryKey() {
        return Keys.DYNAMICINFORMATION_PKEY;
    }

    @Override
    public Vehinformation as(String alias) {
        return new Vehinformation(DSL.name(alias), this);
    }

    @Override
    public Vehinformation as(Name alias) {
        return new Vehinformation(alias, this);
    }

    @Override
    public Vehinformation as(Table<?> alias) {
        return new Vehinformation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vehinformation rename(String name) {
        return new Vehinformation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vehinformation rename(Name name) {
        return new Vehinformation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vehinformation rename(Table<?> name) {
        return new Vehinformation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation where(Condition condition) {
        return new Vehinformation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vehinformation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vehinformation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vehinformation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Vehinformation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Vehinformation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
