/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.rohingillgallon.jooq.model.tables.Accuratebatteryinfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccuratebatteryinfoRecord extends UpdatableRecordImpl<AccuratebatteryinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.accuratebatteryinfo.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo.iotdevicename</code>.
     */
    public void setIotdevicename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.iotdevicename</code>.
     */
    public String getIotdevicename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo.consumption</code>.
     */
    public void setConsumption(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.consumption</code>.
     */
    public Double getConsumption() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo.flowid</code>.
     */
    public void setFlowid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.flowid</code>.
     */
    public Integer getFlowid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo.nopackets</code>.
     */
    public void setNopackets(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.nopackets</code>.
     */
    public Double getNopackets() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.accuratebatteryinfo.time</code>.
     */
    public void setTime(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.accuratebatteryinfo.time</code>.
     */
    public Double getTime() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccuratebatteryinfoRecord
     */
    public AccuratebatteryinfoRecord() {
        super(Accuratebatteryinfo.ACCURATEBATTERYINFO);
    }

    /**
     * Create a detached, initialised AccuratebatteryinfoRecord
     */
    public AccuratebatteryinfoRecord(Integer uniqueEntryId, String iotdevicename, Double consumption, Integer flowid, Double nopackets, Double time) {
        super(Accuratebatteryinfo.ACCURATEBATTERYINFO);

        setUniqueEntryId(uniqueEntryId);
        setIotdevicename(iotdevicename);
        setConsumption(consumption);
        setFlowid(flowid);
        setNopackets(nopackets);
        setTime(time);
        resetChangedOnNotNull();
    }
}
