/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.rohingillgallon.jooq.model.tables.Hostpowerconsumption;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostpowerconsumptionRecord extends UpdatableRecordImpl<HostpowerconsumptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hostpowerconsumption.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.hostpowerconsumption.dcname</code>.
     */
    public void setDcname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption.dcname</code>.
     */
    public String getDcname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.hostpowerconsumption.energy</code>.
     */
    public void setEnergy(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption.energy</code>.
     */
    public Double getEnergy() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.hostpowerconsumption.hpc_name</code>.
     */
    public void setHpcName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.hostpowerconsumption.hpc_name</code>.
     */
    public String getHpcName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HostpowerconsumptionRecord
     */
    public HostpowerconsumptionRecord() {
        super(Hostpowerconsumption.HOSTPOWERCONSUMPTION);
    }

    /**
     * Create a detached, initialised HostpowerconsumptionRecord
     */
    public HostpowerconsumptionRecord(Integer uniqueEntryId, String dcname, Double energy, String hpcName) {
        super(Hostpowerconsumption.HOSTPOWERCONSUMPTION);

        setUniqueEntryId(uniqueEntryId);
        setDcname(dcname);
        setEnergy(energy);
        setHpcName(hpcName);
        resetChangedOnNotNull();
    }
}
