/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.rohingillgallon.jooq.model.tables.Neighbourschange;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NeighbourschangeRecord extends UpdatableRecordImpl<NeighbourschangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.neighbourschange.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.neighbourschange.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.neighbourschange.rsu_id</code>.
     */
    public void setRsuId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.neighbourschange.rsu_id</code>.
     */
    public String getRsuId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.neighbourschange.time_of_update</code>.
     */
    public void setTimeOfUpdate(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.neighbourschange.time_of_update</code>.
     */
    public Double getTimeOfUpdate() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.neighbourschange.neighbour1</code>.
     */
    public void setNeighbour1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.neighbourschange.neighbour1</code>.
     */
    public String getNeighbour1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.neighbourschange.neighbour2</code>.
     */
    public void setNeighbour2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.neighbourschange.neighbour2</code>.
     */
    public String getNeighbour2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.neighbourschange.neighbour3</code>.
     */
    public void setNeighbour3(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.neighbourschange.neighbour3</code>.
     */
    public String getNeighbour3() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.neighbourschange.ischange</code>.
     */
    public void setIschange(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.neighbourschange.ischange</code>.
     */
    public String getIschange() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.neighbourschange.change1</code>.
     */
    public void setChange1(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.neighbourschange.change1</code>.
     */
    public String getChange1() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.neighbourschange.change2</code>.
     */
    public void setChange2(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.neighbourschange.change2</code>.
     */
    public String getChange2() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.neighbourschange.change3</code>.
     */
    public void setChange3(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.neighbourschange.change3</code>.
     */
    public String getChange3() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.neighbourschange.change4</code>.
     */
    public void setChange4(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.neighbourschange.change4</code>.
     */
    public String getChange4() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NeighbourschangeRecord
     */
    public NeighbourschangeRecord() {
        super(Neighbourschange.NEIGHBOURSCHANGE);
    }

    /**
     * Create a detached, initialised NeighbourschangeRecord
     */
    public NeighbourschangeRecord(Integer uniqueEntryId, String rsuId, Double timeOfUpdate, String neighbour1, String neighbour2, String neighbour3, String ischange, String change1, String change2, String change3, String change4) {
        super(Neighbourschange.NEIGHBOURSCHANGE);

        setUniqueEntryId(uniqueEntryId);
        setRsuId(rsuId);
        setTimeOfUpdate(timeOfUpdate);
        setNeighbour1(neighbour1);
        setNeighbour2(neighbour2);
        setNeighbour3(neighbour3);
        setIschange(ischange);
        setChange1(change1);
        setChange2(change2);
        setChange3(change3);
        setChange4(change4);
        resetChangedOnNotNull();
    }
}
