/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.rohingillgallon.jooq.model.tables.Osmoticappsstats;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OsmoticappsstatsRecord extends UpdatableRecordImpl<OsmoticappsstatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.osmoticappsstats.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.osmoticappsstats.appid</code>.
     */
    public void setAppid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.appid</code>.
     */
    public Integer getAppid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.osmoticappsstats.appname</code>.
     */
    public void setAppname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.appname</code>.
     */
    public String getAppname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.osmoticappsstats.cloudletmisize</code>.
     */
    public void setCloudletmisize(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.cloudletmisize</code>.
     */
    public Double getCloudletmisize() {
        return (Double) get(3);
    }

    /**
     * Setter for
     * <code>public.osmoticappsstats.cloudletproccessingtimebyvm</code>.
     */
    public void setCloudletproccessingtimebyvm(Double value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.osmoticappsstats.cloudletproccessingtimebyvm</code>.
     */
    public Double getCloudletproccessingtimebyvm() {
        return (Double) get(4);
    }

    /**
     * Setter for
     * <code>public.osmoticappsstats.datasizeiotdevicetomel_mb</code>.
     */
    public void setDatasizeiotdevicetomelMb(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.osmoticappsstats.datasizeiotdevicetomel_mb</code>.
     */
    public Integer getDatasizeiotdevicetomelMb() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.osmoticappsstats.datasizemeltovm_mb</code>.
     */
    public void setDatasizemeltovmMb(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.datasizemeltovm_mb</code>.
     */
    public Integer getDatasizemeltovmMb() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.osmoticappsstats.destinationvmname</code>.
     */
    public void setDestinationvmname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.destinationvmname</code>.
     */
    public String getDestinationvmname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.osmoticappsstats.edgeletmisize</code>.
     */
    public void setEdgeletmisize(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.edgeletmisize</code>.
     */
    public Double getEdgeletmisize() {
        return (Double) get(8);
    }

    /**
     * Setter for
     * <code>public.osmoticappsstats.edgeletproccessingtimebymel</code>.
     */
    public void setEdgeletproccessingtimebymel(Double value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.osmoticappsstats.edgeletproccessingtimebymel</code>.
     */
    public Double getEdgeletproccessingtimebymel() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.osmoticappsstats.edgelet_mel_finishtime</code>.
     */
    public void setEdgeletMelFinishtime(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.edgelet_mel_finishtime</code>.
     */
    public Double getEdgeletMelFinishtime() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.osmoticappsstats.edgelet_mel_starttime</code>.
     */
    public void setEdgeletMelStarttime(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.edgelet_mel_starttime</code>.
     */
    public Double getEdgeletMelStarttime() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.osmoticappsstats.finishtime</code>.
     */
    public void setFinishtime(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.finishtime</code>.
     */
    public Double getFinishtime() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.osmoticappsstats.iotdevicename</code>.
     */
    public void setIotdevicename(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.iotdevicename</code>.
     */
    public String getIotdevicename() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.osmoticappsstats.melname</code>.
     */
    public void setMelname(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.melname</code>.
     */
    public String getMelname() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.osmoticappsstats.melendtransmissiontime</code>.
     */
    public void setMelendtransmissiontime(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.melendtransmissiontime</code>.
     */
    public Double getMelendtransmissiontime() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.osmoticappsstats.melstarttransmissiontime</code>.
     */
    public void setMelstarttransmissiontime(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.melstarttransmissiontime</code>.
     */
    public Double getMelstarttransmissiontime() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.osmoticappsstats.starttime</code>.
     */
    public void setStarttime(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.starttime</code>.
     */
    public Double getStarttime() {
        return (Double) get(17);
    }

    /**
     * Setter for <code>public.osmoticappsstats.oas_transaction</code>.
     */
    public void setOasTransaction(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.oas_transaction</code>.
     */
    public Integer getOasTransaction() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.osmoticappsstats.transactiontotaltime</code>.
     */
    public void setTransactiontotaltime(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.transactiontotaltime</code>.
     */
    public Double getTransactiontotaltime() {
        return (Double) get(19);
    }

    /**
     * Setter for
     * <code>public.osmoticappsstats.transmissiontimeiotdevicetomel</code>.
     */
    public void setTransmissiontimeiotdevicetomel(Double value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>public.osmoticappsstats.transmissiontimeiotdevicetomel</code>.
     */
    public Double getTransmissiontimeiotdevicetomel() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>public.osmoticappsstats.transmissiontimemeltovm</code>.
     */
    public void setTransmissiontimemeltovm(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.transmissiontimemeltovm</code>.
     */
    public Double getTransmissiontimemeltovm() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>public.osmoticappsstats.flowiotmelappid</code>.
     */
    public void setFlowiotmelappid(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.flowiotmelappid</code>.
     */
    public Integer getFlowiotmelappid() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.osmoticappsstats.flowmelcloudappid</code>.
     */
    public void setFlowmelcloudappid(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.flowmelcloudappid</code>.
     */
    public Integer getFlowmelcloudappid() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.osmoticappsstats.path_dst</code>.
     */
    public void setPathDst(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.path_dst</code>.
     */
    public String getPathDst() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.osmoticappsstats.path_src</code>.
     */
    public void setPathSrc(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.path_src</code>.
     */
    public String getPathSrc() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.osmoticappsstats.edgetowanbw</code>.
     */
    public void setEdgetowanbw(Double value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.osmoticappsstats.edgetowanbw</code>.
     */
    public Double getEdgetowanbw() {
        return (Double) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OsmoticappsstatsRecord
     */
    public OsmoticappsstatsRecord() {
        super(Osmoticappsstats.OSMOTICAPPSSTATS);
    }

    /**
     * Create a detached, initialised OsmoticappsstatsRecord
     */
    public OsmoticappsstatsRecord(Integer uniqueEntryId, Integer appid, String appname, Double cloudletmisize, Double cloudletproccessingtimebyvm, Integer datasizeiotdevicetomelMb, Integer datasizemeltovmMb, String destinationvmname, Double edgeletmisize, Double edgeletproccessingtimebymel, Double edgeletMelFinishtime, Double edgeletMelStarttime, Double finishtime, String iotdevicename, String melname, Double melendtransmissiontime, Double melstarttransmissiontime, Double starttime, Integer oasTransaction, Double transactiontotaltime, Double transmissiontimeiotdevicetomel, Double transmissiontimemeltovm, Integer flowiotmelappid, Integer flowmelcloudappid, String pathDst, String pathSrc, Double edgetowanbw) {
        super(Osmoticappsstats.OSMOTICAPPSSTATS);

        setUniqueEntryId(uniqueEntryId);
        setAppid(appid);
        setAppname(appname);
        setCloudletmisize(cloudletmisize);
        setCloudletproccessingtimebyvm(cloudletproccessingtimebyvm);
        setDatasizeiotdevicetomelMb(datasizeiotdevicetomelMb);
        setDatasizemeltovmMb(datasizemeltovmMb);
        setDestinationvmname(destinationvmname);
        setEdgeletmisize(edgeletmisize);
        setEdgeletproccessingtimebymel(edgeletproccessingtimebymel);
        setEdgeletMelFinishtime(edgeletMelFinishtime);
        setEdgeletMelStarttime(edgeletMelStarttime);
        setFinishtime(finishtime);
        setIotdevicename(iotdevicename);
        setMelname(melname);
        setMelendtransmissiontime(melendtransmissiontime);
        setMelstarttransmissiontime(melstarttransmissiontime);
        setStarttime(starttime);
        setOasTransaction(oasTransaction);
        setTransactiontotaltime(transactiontotaltime);
        setTransmissiontimeiotdevicetomel(transmissiontimeiotdevicetomel);
        setTransmissiontimemeltovm(transmissiontimemeltovm);
        setFlowiotmelappid(flowiotmelappid);
        setFlowmelcloudappid(flowmelcloudappid);
        setPathDst(pathDst);
        setPathSrc(pathSrc);
        setEdgetowanbw(edgetowanbw);
        resetChangedOnNotNull();
    }
}
