/*
 * This file is generated by jOOQ.
 */
package uk.ncl.rohingillgallon.jooq.model.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.ncl.rohingillgallon.jooq.model.tables.Rsuinformation;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RsuinformationRecord extends UpdatableRecordImpl<RsuinformationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rsuinformation.unique_entry_id</code>.
     */
    public void setUniqueEntryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.rsuinformation.unique_entry_id</code>.
     */
    public Integer getUniqueEntryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.rsuinformation.rsu_id</code>.
     */
    public void setRsuId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.rsuinformation.rsu_id</code>.
     */
    public String getRsuId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.rsuinformation.x</code>.
     */
    public void setX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.rsuinformation.x</code>.
     */
    public Double getX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.rsuinformation.y</code>.
     */
    public void setY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.rsuinformation.y</code>.
     */
    public Double getY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.rsuinformation.simtime</code>.
     */
    public void setSimtime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.rsuinformation.simtime</code>.
     */
    public Double getSimtime() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.rsuinformation.communication_radius</code>.
     */
    public void setCommunicationRadius(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.rsuinformation.communication_radius</code>.
     */
    public Double getCommunicationRadius() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.rsuinformation.max_vehicle_communication</code>.
     */
    public void setMaxVehicleCommunication(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.rsuinformation.max_vehicle_communication</code>.
     */
    public Double getMaxVehicleCommunication() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RsuinformationRecord
     */
    public RsuinformationRecord() {
        super(Rsuinformation.RSUINFORMATION);
    }

    /**
     * Create a detached, initialised RsuinformationRecord
     */
    public RsuinformationRecord(Integer uniqueEntryId, String rsuId, Double x, Double y, Double simtime, Double communicationRadius, Double maxVehicleCommunication) {
        super(Rsuinformation.RSUINFORMATION);

        setUniqueEntryId(uniqueEntryId);
        setRsuId(rsuId);
        setX(x);
        setY(y);
        setSimtime(simtime);
        setCommunicationRadius(communicationRadius);
        setMaxVehicleCommunication(maxVehicleCommunication);
        resetChangedOnNotNull();
    }
}
