/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.BandwidthshareinfoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bandwidthshareinfo extends TableImpl<BandwidthshareinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bandwidthshareinfo</code>
     */
    public static final Bandwidthshareinfo BANDWIDTHSHAREINFO = new Bandwidthshareinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BandwidthshareinfoRecord> getRecordType() {
        return BandwidthshareinfoRecord.class;
    }

    /**
     * The column <code>public.bandwidthshareinfo.unique_entry_id</code>.
     */
    public final TableField<BandwidthshareinfoRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.bandwidthshareinfo.bandwidthshare</code>.
     */
    public final TableField<BandwidthshareinfoRecord, Double> BANDWIDTHSHARE = createField(DSL.name("bandwidthshare"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo.channelid</code>.
     */
    public final TableField<BandwidthshareinfoRecord, String> CHANNELID = createField(DSL.name("channelid"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo.edgename</code>.
     */
    public final TableField<BandwidthshareinfoRecord, String> EDGENAME = createField(DSL.name("edgename"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo.melname</code>.
     */
    public final TableField<BandwidthshareinfoRecord, String> MELNAME = createField(DSL.name("melname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.bandwidthshareinfo.timestamp</code>.
     */
    public final TableField<BandwidthshareinfoRecord, Double> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Bandwidthshareinfo(Name alias, Table<BandwidthshareinfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Bandwidthshareinfo(Name alias, Table<BandwidthshareinfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bandwidthshareinfo</code> table reference
     */
    public Bandwidthshareinfo(String alias) {
        this(DSL.name(alias), BANDWIDTHSHAREINFO);
    }

    /**
     * Create an aliased <code>public.bandwidthshareinfo</code> table reference
     */
    public Bandwidthshareinfo(Name alias) {
        this(alias, BANDWIDTHSHAREINFO);
    }

    /**
     * Create a <code>public.bandwidthshareinfo</code> table reference
     */
    public Bandwidthshareinfo() {
        this(DSL.name("bandwidthshareinfo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<BandwidthshareinfoRecord, Integer> getIdentity() {
        return (Identity<BandwidthshareinfoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<BandwidthshareinfoRecord> getPrimaryKey() {
        return Keys.BANDWIDTHSHAREINFO_PKEY;
    }

    @Override
    public Bandwidthshareinfo as(String alias) {
        return new Bandwidthshareinfo(DSL.name(alias), this);
    }

    @Override
    public Bandwidthshareinfo as(Name alias) {
        return new Bandwidthshareinfo(alias, this);
    }

    @Override
    public Bandwidthshareinfo as(Table<?> alias) {
        return new Bandwidthshareinfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bandwidthshareinfo rename(String name) {
        return new Bandwidthshareinfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bandwidthshareinfo rename(Name name) {
        return new Bandwidthshareinfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bandwidthshareinfo rename(Table<?> name) {
        return new Bandwidthshareinfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo where(Condition condition) {
        return new Bandwidthshareinfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bandwidthshareinfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bandwidthshareinfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bandwidthshareinfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Bandwidthshareinfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Bandwidthshareinfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
