/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.ConnectionpersimtimeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Connectionpersimtime extends TableImpl<ConnectionpersimtimeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.connectionpersimtime</code>
     */
    public static final Connectionpersimtime CONNECTIONPERSIMTIME = new Connectionpersimtime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConnectionpersimtimeRecord> getRecordType() {
        return ConnectionpersimtimeRecord.class;
    }

    /**
     * The column <code>public.connectionpersimtime.unique_entry_id</code>.
     */
    public final TableField<ConnectionpersimtimeRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.connectionpersimtime.iotdevices</code>.
     */
    public final TableField<ConnectionpersimtimeRecord, Integer> IOTDEVICES = createField(DSL.name("iotdevices"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.connectionpersimtime.edgehost</code>.
     */
    public final TableField<ConnectionpersimtimeRecord, String> EDGEHOST = createField(DSL.name("edgehost"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.connectionpersimtime.cps_time</code>.
     */
    public final TableField<ConnectionpersimtimeRecord, Double> CPS_TIME = createField(DSL.name("cps_time"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Connectionpersimtime(Name alias, Table<ConnectionpersimtimeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Connectionpersimtime(Name alias, Table<ConnectionpersimtimeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.connectionpersimtime</code> table
     * reference
     */
    public Connectionpersimtime(String alias) {
        this(DSL.name(alias), CONNECTIONPERSIMTIME);
    }

    /**
     * Create an aliased <code>public.connectionpersimtime</code> table
     * reference
     */
    public Connectionpersimtime(Name alias) {
        this(alias, CONNECTIONPERSIMTIME);
    }

    /**
     * Create a <code>public.connectionpersimtime</code> table reference
     */
    public Connectionpersimtime() {
        this(DSL.name("connectionpersimtime"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ConnectionpersimtimeRecord, Integer> getIdentity() {
        return (Identity<ConnectionpersimtimeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConnectionpersimtimeRecord> getPrimaryKey() {
        return Keys.CONNECTIONPERSIMTIME_PKEY;
    }

    @Override
    public Connectionpersimtime as(String alias) {
        return new Connectionpersimtime(DSL.name(alias), this);
    }

    @Override
    public Connectionpersimtime as(Name alias) {
        return new Connectionpersimtime(alias, this);
    }

    @Override
    public Connectionpersimtime as(Table<?> alias) {
        return new Connectionpersimtime(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Connectionpersimtime rename(String name) {
        return new Connectionpersimtime(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Connectionpersimtime rename(Name name) {
        return new Connectionpersimtime(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Connectionpersimtime rename(Table<?> name) {
        return new Connectionpersimtime(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime where(Condition condition) {
        return new Connectionpersimtime(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connectionpersimtime where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connectionpersimtime where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connectionpersimtime where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Connectionpersimtime where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Connectionpersimtime whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
