/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.HistoryentryRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Historyentry extends TableImpl<HistoryentryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.historyentry</code>
     */
    public static final Historyentry HISTORYENTRY = new Historyentry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HistoryentryRecord> getRecordType() {
        return HistoryentryRecord.class;
    }

    /**
     * The column <code>public.historyentry.unique_entry_id</code>.
     */
    public final TableField<HistoryentryRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.historyentry.numactiveports</code>.
     */
    public final TableField<HistoryentryRecord, Integer> NUMACTIVEPORTS = createField(DSL.name("numactiveports"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.historyentry.starttime</code>.
     */
    public final TableField<HistoryentryRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE, this, "");

    private Historyentry(Name alias, Table<HistoryentryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Historyentry(Name alias, Table<HistoryentryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.historyentry</code> table reference
     */
    public Historyentry(String alias) {
        this(DSL.name(alias), HISTORYENTRY);
    }

    /**
     * Create an aliased <code>public.historyentry</code> table reference
     */
    public Historyentry(Name alias) {
        this(alias, HISTORYENTRY);
    }

    /**
     * Create a <code>public.historyentry</code> table reference
     */
    public Historyentry() {
        this(DSL.name("historyentry"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<HistoryentryRecord, Integer> getIdentity() {
        return (Identity<HistoryentryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HistoryentryRecord> getPrimaryKey() {
        return Keys.HISTORYENTRY_PKEY;
    }

    @Override
    public Historyentry as(String alias) {
        return new Historyentry(DSL.name(alias), this);
    }

    @Override
    public Historyentry as(Name alias) {
        return new Historyentry(alias, this);
    }

    @Override
    public Historyentry as(Table<?> alias) {
        return new Historyentry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Historyentry rename(String name) {
        return new Historyentry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Historyentry rename(Name name) {
        return new Historyentry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Historyentry rename(Table<?> name) {
        return new Historyentry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry where(Condition condition) {
        return new Historyentry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Historyentry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Historyentry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Historyentry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Historyentry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Historyentry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
