/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.HostpowerconsumptionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hostpowerconsumption extends TableImpl<HostpowerconsumptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.hostpowerconsumption</code>
     */
    public static final Hostpowerconsumption HOSTPOWERCONSUMPTION = new Hostpowerconsumption();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostpowerconsumptionRecord> getRecordType() {
        return HostpowerconsumptionRecord.class;
    }

    /**
     * The column <code>public.hostpowerconsumption.unique_entry_id</code>.
     */
    public final TableField<HostpowerconsumptionRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.hostpowerconsumption.dcname</code>.
     */
    public final TableField<HostpowerconsumptionRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.hostpowerconsumption.energy</code>.
     */
    public final TableField<HostpowerconsumptionRecord, Double> ENERGY = createField(DSL.name("energy"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.hostpowerconsumption.hpc_name</code>.
     */
    public final TableField<HostpowerconsumptionRecord, String> HPC_NAME = createField(DSL.name("hpc_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Hostpowerconsumption(Name alias, Table<HostpowerconsumptionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Hostpowerconsumption(Name alias, Table<HostpowerconsumptionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.hostpowerconsumption</code> table
     * reference
     */
    public Hostpowerconsumption(String alias) {
        this(DSL.name(alias), HOSTPOWERCONSUMPTION);
    }

    /**
     * Create an aliased <code>public.hostpowerconsumption</code> table
     * reference
     */
    public Hostpowerconsumption(Name alias) {
        this(alias, HOSTPOWERCONSUMPTION);
    }

    /**
     * Create a <code>public.hostpowerconsumption</code> table reference
     */
    public Hostpowerconsumption() {
        this(DSL.name("hostpowerconsumption"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<HostpowerconsumptionRecord, Integer> getIdentity() {
        return (Identity<HostpowerconsumptionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HostpowerconsumptionRecord> getPrimaryKey() {
        return Keys.HOSTPOWERCONSUMPTION_PKEY;
    }

    @Override
    public Hostpowerconsumption as(String alias) {
        return new Hostpowerconsumption(DSL.name(alias), this);
    }

    @Override
    public Hostpowerconsumption as(Name alias) {
        return new Hostpowerconsumption(alias, this);
    }

    @Override
    public Hostpowerconsumption as(Table<?> alias) {
        return new Hostpowerconsumption(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hostpowerconsumption rename(String name) {
        return new Hostpowerconsumption(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hostpowerconsumption rename(Name name) {
        return new Hostpowerconsumption(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hostpowerconsumption rename(Table<?> name) {
        return new Hostpowerconsumption(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption where(Condition condition) {
        return new Hostpowerconsumption(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hostpowerconsumption where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hostpowerconsumption where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hostpowerconsumption where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hostpowerconsumption where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hostpowerconsumption whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
