/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.OverallappresultsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Overallappresults extends TableImpl<OverallappresultsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.overallappresults</code>
     */
    public static final Overallappresults OVERALLAPPRESULTS = new Overallappresults();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OverallappresultsRecord> getRecordType() {
        return OverallappresultsRecord.class;
    }

    /**
     * The column <code>public.overallappresults.unique_entry_id</code>.
     */
    public final TableField<OverallappresultsRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.overallappresults.appname</code>.
     */
    public final TableField<OverallappresultsRecord, String> APPNAME = createField(DSL.name("appname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.endtime</code>.
     */
    public final TableField<OverallappresultsRecord, Double> ENDTIME = createField(DSL.name("endtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column
     * <code>public.overallappresults.iotdevicebatteryconsumption</code>.
     */
    public final TableField<OverallappresultsRecord, Double> IOTDEVICEBATTERYCONSUMPTION = createField(DSL.name("iotdevicebatteryconsumption"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.iotdevicedrained</code>.
     */
    public final TableField<OverallappresultsRecord, String> IOTDEVICEDRAINED = createField(DSL.name("iotdevicedrained"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.simluationtime</code>.
     */
    public final TableField<OverallappresultsRecord, Double> SIMLUATIONTIME = createField(DSL.name("simluationtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.starttime</code>.
     */
    public final TableField<OverallappresultsRecord, Double> STARTTIME = createField(DSL.name("starttime"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.totalcloudletsizes</code>.
     */
    public final TableField<OverallappresultsRecord, Integer> TOTALCLOUDLETSIZES = createField(DSL.name("totalcloudletsizes"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.totaledgeletsizes</code>.
     */
    public final TableField<OverallappresultsRecord, Integer> TOTALEDGELETSIZES = createField(DSL.name("totaledgeletsizes"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.totaliotgenerateddata</code>.
     */
    public final TableField<OverallappresultsRecord, Integer> TOTALIOTGENERATEDDATA = createField(DSL.name("totaliotgenerateddata"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.totalmelgenerateddata</code>.
     */
    public final TableField<OverallappresultsRecord, Integer> TOTALMELGENERATEDDATA = createField(DSL.name("totalmelgenerateddata"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.overallappresults.apptotalrunningtime</code>.
     */
    public final TableField<OverallappresultsRecord, Double> APPTOTALRUNNINGTIME = createField(DSL.name("apptotalrunningtime"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Overallappresults(Name alias, Table<OverallappresultsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Overallappresults(Name alias, Table<OverallappresultsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.overallappresults</code> table reference
     */
    public Overallappresults(String alias) {
        this(DSL.name(alias), OVERALLAPPRESULTS);
    }

    /**
     * Create an aliased <code>public.overallappresults</code> table reference
     */
    public Overallappresults(Name alias) {
        this(alias, OVERALLAPPRESULTS);
    }

    /**
     * Create a <code>public.overallappresults</code> table reference
     */
    public Overallappresults() {
        this(DSL.name("overallappresults"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OverallappresultsRecord, Integer> getIdentity() {
        return (Identity<OverallappresultsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OverallappresultsRecord> getPrimaryKey() {
        return Keys.OVERALLAPPRESULTS_PKEY;
    }

    @Override
    public Overallappresults as(String alias) {
        return new Overallappresults(DSL.name(alias), this);
    }

    @Override
    public Overallappresults as(Name alias) {
        return new Overallappresults(alias, this);
    }

    @Override
    public Overallappresults as(Table<?> alias) {
        return new Overallappresults(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Overallappresults rename(String name) {
        return new Overallappresults(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Overallappresults rename(Name name) {
        return new Overallappresults(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Overallappresults rename(Table<?> name) {
        return new Overallappresults(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults where(Condition condition) {
        return new Overallappresults(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Overallappresults where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Overallappresults where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Overallappresults where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Overallappresults where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Overallappresults whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
