/*
 * This file is generated by jOOQ.
 */
package uk.ncl.giacomobergami.utils.database.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.ncl.giacomobergami.utils.database.jooq.Keys;
import uk.ncl.giacomobergami.utils.database.jooq.Public;
import uk.ncl.giacomobergami.utils.database.jooq.tables.records.SwitchpowerconsumptionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Switchpowerconsumption extends TableImpl<SwitchpowerconsumptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.switchpowerconsumption</code>
     */
    public static final Switchpowerconsumption SWITCHPOWERCONSUMPTION = new Switchpowerconsumption();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SwitchpowerconsumptionRecord> getRecordType() {
        return SwitchpowerconsumptionRecord.class;
    }

    /**
     * The column <code>public.switchpowerconsumption.unique_entry_id</code>.
     */
    public final TableField<SwitchpowerconsumptionRecord, Integer> UNIQUE_ENTRY_ID = createField(DSL.name("unique_entry_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.switchpowerconsumption.dcname</code>.
     */
    public final TableField<SwitchpowerconsumptionRecord, String> DCNAME = createField(DSL.name("dcname"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.switchpowerconsumption.energy</code>.
     */
    public final TableField<SwitchpowerconsumptionRecord, Double> ENERGY = createField(DSL.name("energy"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.switchpowerconsumption.spc_name</code>.
     */
    public final TableField<SwitchpowerconsumptionRecord, String> SPC_NAME = createField(DSL.name("spc_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Switchpowerconsumption(Name alias, Table<SwitchpowerconsumptionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Switchpowerconsumption(Name alias, Table<SwitchpowerconsumptionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.switchpowerconsumption</code> table
     * reference
     */
    public Switchpowerconsumption(String alias) {
        this(DSL.name(alias), SWITCHPOWERCONSUMPTION);
    }

    /**
     * Create an aliased <code>public.switchpowerconsumption</code> table
     * reference
     */
    public Switchpowerconsumption(Name alias) {
        this(alias, SWITCHPOWERCONSUMPTION);
    }

    /**
     * Create a <code>public.switchpowerconsumption</code> table reference
     */
    public Switchpowerconsumption() {
        this(DSL.name("switchpowerconsumption"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SwitchpowerconsumptionRecord, Integer> getIdentity() {
        return (Identity<SwitchpowerconsumptionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SwitchpowerconsumptionRecord> getPrimaryKey() {
        return Keys.SWITCHPOWERCONSUMPTION_PKEY;
    }

    @Override
    public Switchpowerconsumption as(String alias) {
        return new Switchpowerconsumption(DSL.name(alias), this);
    }

    @Override
    public Switchpowerconsumption as(Name alias) {
        return new Switchpowerconsumption(alias, this);
    }

    @Override
    public Switchpowerconsumption as(Table<?> alias) {
        return new Switchpowerconsumption(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Switchpowerconsumption rename(String name) {
        return new Switchpowerconsumption(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Switchpowerconsumption rename(Name name) {
        return new Switchpowerconsumption(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Switchpowerconsumption rename(Table<?> name) {
        return new Switchpowerconsumption(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption where(Condition condition) {
        return new Switchpowerconsumption(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Switchpowerconsumption where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Switchpowerconsumption where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Switchpowerconsumption where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Switchpowerconsumption where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Switchpowerconsumption whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
